/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as studentErc20Sol from "./studentERC20.sol";
export { StudentSocietyDAO__factory } from "./StudentSocietyDAO__factory";
export { BonusERC721__factory } from "./BonusERC721__factory";
