/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as studentErc20Sol from "./studentERC20.sol";
export type { studentErc20Sol };
export type { StudentSocietyDAO } from "./StudentSocietyDAO";
export type { BonusERC721 } from "./BonusERC721";
